# Spec: https://xrpl.org/xrp-ledger-toml.html

[METADATA]
modified = 2024-01-04T12:12:12.000Z

[[VALIDATORS]]
public_key = "nHUUVLx2a8d7QbTwsFw2oVqun3YvyMaydMJYfvZba8tYhaKBwWxi"
attestation="3BC8A848A299E64C5A5DE8BB99BA1514C2940BD9FC46EA646C87E17FEF773642BBD32456578A9B74BB97FEFBEB8788A0639F6F497C2DEED1AC474EDB60A82500"
network = "main"
owner_country = "CL"
server_country = "CL"
server_location = "Private datacenter (Puerto Varas area, CL)"
server_cloud = false
network_asn = 14117
desc = "Validator"

unl = ["https://vl.xahau.org"]

[[PRINCIPALS]]
name = "Lathan"
twitter = "ShortTheFOMO"

# End of file
