# Spec: https://xrpl.org/xrp-ledger-toml.html

[METADATA]
modified = 2025-01-21T12:12:12.000Z

[[VALIDATORS]]
public_key = "nHUNoV59PdKmyN42WGH6jG9ZmGJdsvn1oRHK5qzpmAs6awckZ92h"
attestation="9572F77F7CEFC0475FE8F4F8C9877CB790DCE4E6778B6532DBC899466E91E23FBB0EF317B2F78B5D2DABE2407FCD3F485E9E48181B6E1569DBB37B6E228AF600"
network = "main"
owner_country = "CL"
server_country = "NL"
server_location = "HOSTCIRCLE-L-, NL"
server_cloud = false
network_asn = 56504
desc = "Validator"

unl = ["https://vl.ripple.com", "https://vl.xrplf.org"]

[[PRINCIPALS]]
name = "Lathan"
twitter = "ShortTheFOMO"

# End of file
