# Spec: https://xrpl.org/xrp-ledger-toml.html

[METADATA]
modified = 2024-01-04T12:12:12.000Z

[[VALIDATORS]]
public_key = "nHBiXWRTwVeDCux4hXsD1AHg96paDtK8AALJ6cCy3UBCzF86h8VA"
attestation="B7E764F7D2181E078BC886938A608A2357B5182E07D28E94AC85AA1F62D6E6F25E901F00ED93CCE520D09198DDFF8666992873A60BD53DFBEC8B07F2521D9502"
network = "mainnet"
owner_country = "CL"
server_country = "CL"
server_location = "Private datacenter (Puerto Varas area, CL)"
server_cloud = false
network_asn = 14117
desc = "Validator"

unl = "https://vl.xrplf.org"

[[PRINCIPALS]]
name = "Lathan"
twitter = "ShortTheFOMO"

[[SERVERS]]
public_key = "n9Mife6h1Sh1YwuFwYVwViGjUND5dvAYRpvSRt9mtWvsTCvYgnMe"
rpc = "https://xrpl.panicbot.app:51234"
peer = "https://xrpl.panicbot.app:51235"
ws = "wss://xrpl.panicbot.app"
network = "mainnet"
owner_country = "CL"
server_country = "FI"
server_location = "Hetzner, DE"
server_cloud = true
network_asn = 24940
desc = "General purpose server cluster"

[[SERVERS]]
public_key = "n9LSD741wwvy6VgxRJibY7gY5TsoEpbNYSzjqAtNHL2JVDzc2pwu"
rpc = "https://node.panicbot.xyz:51234"
peer = "https://node.panicbot.xyz:51235"
ws = "wss://node.panicbot.xyz"
network = "mainnet"
owner_country = "CL"
server_country = "FI"
server_location = "Hetzner, DE"
server_cloud = true
network_asn = 24940
desc = "General purpose server cluster"

# End of file
